version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: ./server
    restart: always
    environment:
      PORT: ${SERVER_PORT}
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    env_file:
      - ./.env 
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    restart: always
    ports:
      - "${CLIENT_PORT}:80"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  db-data: